version: '3.4'

networks:
  dev:
    driver: bridge

services:
  clinicapp:
    image: docker.io/library/clinicapp
    depends_on:
      - "clinicdb"
    container_name: clinicscheduler
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionString__DefaultConnection=User ID= postgres;Password=ClinicDb123;Server=clinicdb;Port=5432;Database=ClinicDb;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  clinicdb: 
    image: postgres:latest
    container_name: clinicdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ClinicDb
      POSTGRES_PASSWORD: ClinicDb123
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql
    networks:
      - dev

volumes: 
  app_data: